name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M')"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - uses: docker/login-action@v3
      name: Docker Auth
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_IMAGE }}:latest,${{ secrets.DOCKERHUB_IMAGE }}:${{ steps.date.outputs.date }}
    - name: Deploy Dev
      if: github.ref != "refs/heads/master"
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{secrets.API_KEY}}" \
          -H "Content-Type: application/json" \
          "${{secrets.RENDER_HOOK_DEV}}"
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{secrets.API_KEY}}" \
          -H "Content-Type: application/json" \
          "${{secrets.RENDER_HOOK}}"
